# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitfresh < Formula
  desc "A DX Tool to keep the git repositories updated"
  homepage "https://github.com/apolo96/xwdgrap"
  version "1.0.0"
  license "MIT"

  depends_on "git"

  on_macos do
    on_intel do
      url "https://github.com/apolo96/gitfresh/releases/download/v1.0.0/gitfresh_Darwin_x86_64.tar.gz"
      sha256 "d45525985b68826c8af5323e7227cfbaac01310d504dba2ccc5831cef8c76592"

      def install
        bin.install "gitfresh"
        bin.install "gitfreshd"
      end
    end
    on_arm do
      url "https://github.com/apolo96/gitfresh/releases/download/v1.0.0/gitfresh_Darwin_arm64.tar.gz"
      sha256 "3c3ebb41508bae5e8b415534f5ab3180362d6d2d7278cdc462abbbb6d3b5c89b"

      def install
        bin.install "gitfresh"
        bin.install "gitfreshd"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/apolo96/gitfresh/releases/download/v1.0.0/gitfresh_Linux_x86_64.tar.gz"
        sha256 "05842485ef5b6daacc6df218b65d68053ad787500b1fcc6172af16eb338e888d"

        def install
          bin.install "gitfresh"
          bin.install "gitfreshd"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/apolo96/gitfresh/releases/download/v1.0.0/gitfresh_Linux_armv7.tar.gz"
        sha256 "9054315bc5619e15d44282b82b148eacc90afdaeed5b344dc9c50c25ccfaf23f"

        def install
          bin.install "gitfresh"
          bin.install "gitfreshd"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/apolo96/gitfresh/releases/download/v1.0.0/gitfresh_Linux_arm64.tar.gz"
        sha256 "5d6d9086042fcff1322387057f29982c08bbe9c597ea20e15fa16ff1c48693fa"

        def install
          bin.install "gitfresh"
          bin.install "gitfreshd"
        end
      end
    end
  end

  test do
    system "#{bin}/gitfresh version"
  end
end
